apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: mongo:latest
          command: ["mongod", "--port", "27017", "--bind_ip_all"]
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: database
            - name: MONGO_INITDB_ROOT_USERNAME
              value: user
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password
---

---

---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: ttl.sh/university-parking:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_HOST
              value: database
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_DATABASE
              value: database
            - name: MONGODB_USERNAME
              value: user
            - name: MONGODB_PASSWORD
              value: password
